apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: mvdream-lyg-b-a-50
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          affinity:           
            nodeAffinity:              
              requiredDuringSchedulingIgnoredDuringExecution:                
                nodeSelectorTerms:                  
                  - matchExpressions:                      
                    - key: "scattered-gpu-pool"                        
                      operator: Exists
          imagePullSecrets:
            - name: vast-secret
          containers:
          - image: ccr-23gxup9u-vpc.cnc.bj.baidubce.com/model/ts3d:v_magic123_2_mv
            name: pytorch
            securityContext:
              capabilities:
                add: ["IPC_LOCK"]
            resources:
              limits:
                baidu.com/a800_80g_cgpu: "1"
              requests:
                baidu.com/a800_80g_cgpu: "1"
            command:
              - "/bin/sh"
              - "-c"
              # - "sleep inf"
              - "cd /mnt/pfs/users/liyangguang/vastcode/threestudio && export OMP_NUM_THREADS=1 && python launch.py --config configs/mvdream-sd21-vast-rgb-normal.yaml --train --gpu 0 system.prompt_processor.prompt='a DSLR photo of a squirrel playing guitar'"
            env:
              - name: NCCL_DEBUG
                value: INFO
              - name: NCCL_IB_DISABLE
                value: "0"
              - name: LOCAL_RANK
                value: "0"
            volumeMounts:
              - mountPath: /mnt/pfs
                name: pfs
              - mountPath: /dev/shm
                name: cache-volume
          volumes:
            - name: pfs
              hostPath:
                path: /mnt/pfs
            - emptyDir:
                medium: Memory
              name: cache-volume
          priorityClassName: normal
          schedulerName: volcano
