name: mvdream
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: /mnt/pfs/users/liuyingtian/3dstudio/exps
seed: 0


data_type: "random-camera-uniform-view-datamodule"
data:
  batch_size: [8, 8]
  n_uniform_views: ${system.guidance.n_multi_views}
  # 0-4999: 64x64, >=5000: 512x512
  # this drastically reduces VRAM usage as empty space is pruned in early training
  width: [64, 256]
  height: [64, 256]
  resolution_milestones: [2000]
  camera_distance_range: [2.4, 2.4]
  fovy_range: [39.5977, 39.5977]
  elevation_range: [0., 30.]
  azimuth_range: [0., 90.]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  eval_camera_distance: 2.4
  eval_fovy_deg: 40.
  n_val_views: 4

  light_position_perturb: 1 
  light_distance_range: [2.0,2.4]
  light_sample_strategy: dreamfusion

system_type: mvdream-system
system:
  geometry_type: "implicit-volume"
  geometry:
    radius: 0.5
    normal_type: analytic

    density_bias: "blob_magic3d"
    density_activation: softplus
    density_blob_scale: 10.
    density_blob_std: 0.5

    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378 # max resolution 4096

  material_type: "no-material"
  material:
    n_output_dims: 3
    color_activation: sigmoid
  # material_type: "diffuse-with-point-light-material"
  # material:
  #   ambient_only_steps: 2001
  #   albedo_activation: sigmoid

  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid
    random_aug: false
    random_aug_prob: 0.5

  renderer_type: "nerf-volume-renderer"
  renderer:
    radius: ${system.geometry.radius}
    num_samples_per_ray: 512

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: /mnt/pfs/users/liuzexiang/Code/tune-a-video/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/133a221b8aa7292a167afc5127cb63fb5005638b
    prompt: ???

    prompt_front: ${system.prompt_processor.prompt}
    prompt_side: ${system.prompt_processor.prompt}
    prompt_back: ${system.prompt_processor.prompt}
    prompt_overhead: ${system.prompt_processor.prompt}
    front_threshold: 30.
    back_threshold: 30.

  guidance_type: multiview-unified-guidance
  guidance:
    guidance_type: sds
    pretrained_model_name_or_path: /mnt/pfs/users/liuzexiang/Code/tune-a-video/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/133a221b8aa7292a167afc5127cb63fb5005638b
    unet_path: /mnt/pfs/users/liyangguang/vastcode/tune-a-video/outputs/render-group-1-2-laion-ga-3dword-gray-laion20M
    guidance_scale: 100.0
    weighting_strategy: dreamfusion
    min_step_percent: [0, 0.98, 0.02, 8000]
    max_step_percent: [0, 0.98, 0.5, 8000]
    n_multi_views: 4
    view_dependent_prompting: false
    half_precision_weights: false
    # return_rgb_1step_orig: true

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_sd: 1.
    # lambda_orient: [0, 10., 1000., 5000]
    lambda_orient: 0.
    lambda_sparsity: 1.
    lambda_opaque: 0.
  optimizer:
    name: AdamW
    lr: 0.01
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15

trainer:
  max_steps: 10000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 200
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
