name: "unidream"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs/unidream-only-geometry"
seed: 0

data_type: "random-camera-uniform-view-datamodule"
data:
  batch_size: [8, 8]
  n_uniform_views: ${system.guidance.n_multi_views}
  # 0-4999: 64x64, >=5000: 512x512
  # this drastically reduces VRAM usage as empty space is pruned in early training
  width: [64, 256]
  height: [64, 256]
  resolution_milestones: [2000]
  camera_distance_range: [2.4, 2.4]
  fovy_range: [39.5977, 39.5977]
  elevation_range: [0., 30.]
  azimuth_range: [0., 90.]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  eval_camera_distance: 2.4
  eval_fovy_deg: 40.
  n_val_views: 4

  light_position_perturb: 1 
  light_distance_range: [2.0,2.4]
  light_sample_strategy: dreamfusion

system_type: "unidream-system"
system:
  stage: only-geometry
  latent_steps: 1000
  geometry_type: "implicit-sdf"
  geometry:
    radius: 1.0
    n_feature_dims: 0
    isosurface_resolution: 128
    isosurface_deformable_grid: true
    isosurface_coarse_to_fine: false

    # initialize SDF by optimization
    shape_init: sphere
    shape_init_params: 0.5

    # or you can initialize SDF using a guide mesh
    # shape_init: mesh:load/shapes/human.obj
    # shape_init_params: 0.9
    # shape_init_mesh_up: +y
    # shape_init_mesh_front: +z

    # an alternative initialization implementation:
    # you can initialize SDF to sphere/ellipsoid by adding a bias value
    # which leads to more smooth initialized shape
    # sdf_bias: sphere
    # sdf_bias_params: 0.5
    # DO NOT use the two initialization methods together

  material_type: "no-material" # unused
  material:
    n_output_dims: 0

  background_type: "solid-color-background" # unused

  renderer_type: "nvdiff-rasterizer"

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: /mnt/pfs/users/liuzexiang/Code/tune-a-video/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/133a221b8aa7292a167afc5127cb63fb5005638b
    prompt: ???

    prompt_front: ${system.prompt_processor.prompt}
    prompt_side: ${system.prompt_processor.prompt}
    prompt_back: ${system.prompt_processor.prompt}
    prompt_overhead: ${system.prompt_processor.prompt}
    front_threshold: 30.
    back_threshold: 30.

  guidance_type: multiview-unified-guidance
  guidance:
    guidance_type: sds
    pretrained_model_name_or_path: /mnt/pfs/users/liuzexiang/Code/tune-a-video/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/133a221b8aa7292a167afc5127cb63fb5005638b
    unet_path: /mnt/pfs/users/liuzexiang/Code/tune-a-video/outputs/lvis50w_gray_nocfg_onlynormal/checkpoint
    guidance_scale: 100.0
    weighting_strategy: dreamfusion
    min_step_percent: [0, 0.98, 0.02, 8000]
    max_step_percent: [0, 0.98, 0.5, 8000]
    n_multi_views: 4
    view_dependent_prompting: false
    half_precision_weights: false
    # return_rgb_1step_orig: true

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_sd: 1.
    lambda_normal_consistency: 0.

  optimizer:
    name: Adam
    args:
      lr: 0.01
      betas: [0.9, 0.99]
      eps: 1.e-15

trainer:
  max_steps: 10000
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  val_check_interval: 200
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
