name: mvdream
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: outputs/dmtet_sd/rgb_basecolor_normal_v2
seed: 0

data_type: "random-camera-datamodule-tex"
data:
  batch_size: 1
  width: 512
  height: 512
  camera_distance_range: [3, 3]
  fovy_range: [45, 45]
  fovy_range_detail: [20, 40]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  elevation_range: [-10, 45]
  elevation_range_detail: [-10, 60]
  azimuth_range: [-180, 180]
  batch_uniform_azimuth: true
  eval_camera_distance: 3.
  eval_fovy_deg: 45.
  # n_val_views: 4
  num_workers: 32
  return_rays: false  
  offset_azimuth: 90

system_type: brdfgen-system
system:
  texture: true
  test_reset_light: true
  render_relight: false
  test_light_rotation: true
  test_light_rotate_half: true
  test_light_rotation_all: false
  use_ks_smooth_loss: true
  use_albedo_bg: true
  detach_albedo: true
  reuse_prev_geometry: false
  init_rm_with_value: false
  init_r_value: 0.5
  init_m_value: 0.2
  guidance_alter: false
  # clip_prop: 0.5
  # refinement: true
  # geometry_convert_from: ???
  geometry_convert_inherit_texture: true
  geometry_type: "tetrahedra-sdf-grid"
  geometry:
    radius: 1.0 # consistent with coarse
    isosurface_resolution: 128
    isosurface_deformable_grid: true
    pos_encoding_config: # consistent with coarse, no progressive band
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.4472692374403782 # max resolution 4096
    # n_feature_dims: 9
    fix_geometry: true # optimize grid sdf and deformation
    new_pbr_model: true
    use_new_pbr_encoder: true


  material_type: "pbr-material"
  material:
    material_activation: sigmoid
    use_preload_environment: true
    # environment_texture: "load/lights/mud_road_puresky_1k.hdr"
    # environment_texture: "load/lights/irrmaps/mud_road_puresky_4k.hdr"
    environment_texture: "/mnt/pfs/users/linyoutian/threestudio/load/lights/irrmaps/studio_small_09_4k.hdr"
    # reset_light_path: "/mnt/pfs/users/linyoutian/threestudio/load/lights/irrmaps/high/pump_house_4k.hdr"
    reset_light_path: "/mnt/pfs/users/linyoutian/threestudio/load/lights/irrmaps/high/lapa_4k.hdr"
    environment_scale: 1.0
    test_environment_scale: 1.0
    environment_train: false
    min_metallic: 0.0
    max_metallic: 0.9
    min_roughness: 0.02
    max_roughness: 0.9
    use_bump: false
    albedo_train: true
    roughness_train: true
    metallic_train: true
    use_preset_env_color: false
    color_preset: 0.5
    switch_lights: false
    switch_lights_interval: 1
    light_rotation: true
    use_visiblity: true
    use_auto_gamma: true
    single_channel_light: false
    fix_gamma: true

  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid
    random_aug: True

  renderer_type: "nvdiff-rasterizer-pbr"
  renderer:
    context_type: gl
    positions_jitter: true

  # prompt_processor_type: "stable-diffusion-prompt-processor"
  # prompt_processor:
  #   pretrained_model_name_or_path: stabilityai/stable-diffusion-2-1-base
  #   prompt: ???
  #   negative_prompt: "ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, and unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions"

  # prompt_processor_type_II: "stable-diffusion-prompt-processor"
  # prompt_processor_II:
  #   pretrained_model_name_or_path: stabilityai/stable-diffusion-2-1-base
  #   prompt: ???
  #   negative_prompt: "ugly, highlight, shiny, metallic, reflection, lowres, low quality, cropped, highlight, shiny, metallic, reflection"

  # guidance_type: "stable-diffusion-guidance-trt"
  # guidance:
  #   enable_tiny_vae: true
  #   # unsharp_mask: true
  #   # unsharp_mix_factor: 0.1
  #   pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
  #   weighting_strategy: sds
  #   guidance_scale: 100.0
  #   min_step_percent: 0.02
  #   max_step_percent: 0.5
  #   # view_dependent_prompting: false

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
    prompt: ???
    negative_prompt: "blur, oversaturated, ugly, tiling, low quality, noise, ugly pattern"

  guidance_type: "stable-diffusion-unified-guidance-trt"
  guidance:
    pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
    enable_tiny_vae: true
    guidance_type: "sds"
    guidance_scale: 100.
    weighting_strategy: uniform
    min_step_percent: 0.1
    max_step_percent: 0.5
    controlnet_model_name_or_path:
      - "lllyasviel/control_v11p_sd15_canny"
    controlnet_preprocessor:
      - rgb2canny
    controlnet_input:
      - "normal"
    controlnet_scale:
      - [1000, 0.5, 0.0, 1001]


  prompt_processor_type_II: "stable-diffusion-prompt-processor"
  prompt_processor_II:
    pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
    prompt: ???
    # negative_prompt: "highlight, shiny, metallic, reflection, ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, dull, and unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions, "
    negative_prompt: "highlight, shiny, metallic, reflection, ugly, blurry, pixelated obscure, unnatural colors, unclear, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, "

  guidance_type_II: "stable-diffusion-unified-guidance-trt"
  guidance_II:
    pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
    enable_tiny_vae: true
    guidance_type: "sds"
    guidance_scale: 100.
    weighting_strategy: uniform
    min_step_percent: 0.1
    max_step_percent: 0.5
    controlnet_model_name_or_path:
      - "lllyasviel/control_v11p_sd15_canny"
    controlnet_preprocessor:
      - rgb2canny
    controlnet_input:
      - "normal"
    controlnet_scale:
      - [1000, 0.2, 0.0, 1001]

  # guidance_type_II: "stable-diffusion-guidance-trt"
  # guidance_II:
  #   enable_tiny_vae: true
  #   unsharp_mask: false
  #   unsharp_mix_factor: 0.1
  #   pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
  #   weighting_strategy: sds
  #   guidance_scale: 100.0
  #   min_step_percent: 0.02
  #   max_step_percent: 0.5
  #   # view_dependent_prompting: false

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    # lambda_sds: [100, 0.1, 1., 1000]
    lambda_sds: 1.0
    lambda_sd: 1.0
    # lambda_sds_II: 1.0
    lambda_sds_II: 1.
    lambda_sd_II: 1.
    lambda_normal_consistency: 0.
    lambda_laplacian_smoothness: 0.
    lambda_light_regularizer_white: 0.
    lambda_light_regularizer_tv: 0.
    lambda_metallic_loss: 0.
    lambda_kd_loss: 1.
    # lambda_kd_loss: 100.
    # lambda_kr_loss: [100, 100., 10., 1000]
    # lambda_km_loss: [100, 10., 100., 1000]
    lambda_km_loss: 0.
    lambda_kr_loss: 0.
    lambda_clipimage_loss: 0.

  optimizer:
    name: AdamW
    args:
      lr: 0.01
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      background:
        lr: 0.001
      background_II:
        lr: 0.001
      # material.auto_gamma:
      #   lr: 0.001   
      # material.light:
      #   lr: 0.01   
      geometry.encoding:
        lr: 0.001
      geometry.feature_network:
        lr: 0.01
      geometry.encoding_pbr:
        lr: 0.0001
      geometry.feature_network_pbr:
        lr: 0.01
      # geometry.feature_network_v:
      #   lr: 0.001
      # geometry.feature_network_r:
      #   lr: 0.01
      # geometry.feature_network_m:
      #   lr: 0.01
      # geometry.feature_network_n:
      #   lr: 0.001
      # geometry.sdf:
      #   lr: 0.001
      # geometry.deformation:
      #   lr: 0.001

trainer:
  max_steps: 2000
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  val_check_interval: 200
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: 0
